"""pytest 共享 fixtures"""

from pathlib import Path

import pytest

FIXTURES_DIR = Path(__file__).parent / "fixtures"


@pytest.fixture
def cube_stl_path() -> Path:
    """测试用 10mm 立方体 STL 路径"""
    return FIXTURES_DIR / "cube_10mm.stl"


@pytest.fixture
def sample_gcode_path() -> Path:
    """测试用 G-code 文件路径 (由 conftest 自动生成)"""
    gcode_path = FIXTURES_DIR / "sample.gcode"
    if not gcode_path.exists():
        # 生成模拟 G-code 用于测试解析
        gcode_content = """\
; generated by PrusaSlicer 2.9.4 on 2026-05-14 at 14:42:46 UTC
;
G28 ; home
G1 Z0.2 F500
G1 X10 Y10 E0.5
;LAYER_CHANGE
G1 Z0.4
G1 X20 Y20 E1.0
;LAYER_CHANGE
G1 Z0.6
G1 X30 Y30 E1.5
;LAYER_CHANGE
; filament used [mm] = 150.5
; filament used [cm3] = 0.36
; total filament used [g] = 0.45
; estimated printing time (normal mode) = 5m 30s
"""
        gcode_path.write_text(gcode_content, encoding="utf-8")
    return gcode_path
