"""gcode_parser 单元测试"""

from pathlib import Path

import pytest

from app.services.gcode_parser import GCodeParserService


def test_parse_sample_gcode(sample_gcode_path: Path):
    """测试解析模拟 G-code 文件"""
    parser = GCodeParserService()
    result = parser.parse(sample_gcode_path, "PLA")

    assert result.print_time_seconds == 330.0  # 5m 30s
    assert result.print_time_formatted == "5m 30s"
    assert result.filament_used_mm == pytest.approx(150.5, rel=0.01)
    assert result.filament_used_cm3 == pytest.approx(0.36, rel=0.01)
    assert result.filament_used_grams > 0
    assert result.layer_count == 3
    assert result.slicer_version == "PrusaSlicer 2.9.4"


def test_parse_time_string():
    """测试时间字符串解析"""
    parser = GCodeParserService()

    assert parser._parse_time_string("2h 34m 20s") == 9260
    assert parser._parse_time_string("1h 5m") == 3900
    assert parser._parse_time_string("45m 30s") == 2730
    assert parser._parse_time_string("30s") == 30


def test_filament_grams_from_cm3(sample_gcode_path: Path):
    """测试当 [g] 为 0 时从 [cm3] 计算重量"""
    parser = GCodeParserService()
    result = parser.parse(sample_gcode_path, "PLA")

    # G-code 中 [g] = 0.45，经 round_weight 四舍五入到 0.5
    assert result.filament_used_grams == pytest.approx(0.5, abs=0.01)


def test_filament_grams_fallback():
    """测试 [g] 为 0 时从 cm3 降级计算"""
    from tempfile import NamedTemporaryFile

    gcode = """\
; generated by PrusaSlicer 2.9.4 on 2026-01-01
; filament used [mm] = 100
; filament used [cm3] = 2.0
; total filament used [g] = 0.00
; estimated printing time (normal mode) = 10m
"""
    with NamedTemporaryFile(suffix=".gcode", delete=False, mode="w", encoding="utf-8") as f:
        f.write(gcode)
        path = Path(f.name)

    try:
        parser = GCodeParserService()
        result = parser.parse(path, "PLA")
        # 2.0 cm³ × 1.24 g/cm³ = 2.48g
        assert result.filament_used_grams == pytest.approx(2.48, rel=0.01)
    finally:
        path.unlink(missing_ok=True)
