"""
G-code 解析服务

解析 PrusaSlicer 生成的 G-code 文件，从注释行中提取打印统计信息:
- 打印时间
- 耗材使用量 (长度/体积/重量)
- 切片器版本
- 层数
"""

import re
from pathlib import Path

from app.services.config_service import config_service
from app.models.slicing import SlicingResult
from app.utils.logging_utils import get_logger
from app.utils.math_utils import format_time, round_weight

logger = get_logger(__name__)


class GCodeParserService:
    """PrusaSlicer G-code 解析服务"""

    def parse(self, gcode_path: Path, material: str = "PLA") -> SlicingResult:
        """
        解析 G-code 文件，提取所有统计数据。

        策略: 优先读尾部 10KB (统计信息在文件尾部)，找不到则全文扫描。
        """
        content = self._read_gcode(gcode_path)
        lines = content.splitlines()

        # 提取各项统计数据
        print_time_seconds, print_time_formatted = self._extract_print_time(lines)
        filament_mm, filament_cm3, filament_grams = self._extract_filament_usage(lines, material)
        slicer_version = self._extract_slicer_version(lines)
        layer_count = self._count_layers(lines)

        result = SlicingResult(
            print_time_seconds=print_time_seconds,
            print_time_formatted=print_time_formatted,
            filament_used_mm=round(filament_mm, 1),
            filament_used_grams=round_weight(filament_grams),
            filament_used_cm3=round(filament_cm3, 2),
            layer_count=layer_count,
            gcode_file_size_bytes=gcode_path.stat().st_size,
            slicer_version=slicer_version,
        )

        logger.info(
            "G-code 解析完成: 时间=%s, 耗材=%.1fg, 层数=%d",
            print_time_formatted,
            filament_grams,
            layer_count,
        )
        return result

    def _read_gcode(self, path: Path) -> str:
        """读取 G-code 文件内容"""
        # 先尝试只读尾部 10KB (统计信息通常在文件末尾)
        file_size = path.stat().st_size
        tail_size = min(10240, file_size)

        with open(path, "rb") as f:
            if file_size > tail_size:
                # 读尾部
                f.seek(file_size - tail_size)
                tail = f.read().decode("utf-8", errors="replace")
                # 检查是否包含统计信息
                if "estimated printing time" in tail or "filament used" in tail:
                    # 还需要读头部获取版本号
                    f.seek(0)
                    head_size = min(4096, file_size)
                    head = f.read(head_size).decode("utf-8", errors="replace")
                    return head + "\n" + tail

            # 全文读取
            f.seek(0)
            return f.read().decode("utf-8", errors="replace")

    def _extract_print_time(self, lines: list[str]) -> tuple[float, str]:
        """
        从注释行提取打印时间。
        匹配: ; estimated printing time (normal mode) = 2h 34m 20s
        """
        pattern = re.compile(
            r";\s*estimated printing time\s*\([^)]+\)\s*=\s*(.+)$",
            re.IGNORECASE,
        )
        for line in lines:
            m = pattern.match(line)
            if m:
                time_str = m.group(1).strip()
                seconds = self._parse_time_string(time_str)
                return seconds, format_time(seconds)

        return 0.0, "0s"

    def _extract_filament_usage(
        self, lines: list[str], material: str
    ) -> tuple[float, float, float]:
        """
        从注释行提取耗材使用量。
        匹配:
          ; filament used [mm] = 4235.6
          ; filament used [cm3] = 12.8
          ; total filament used [g] = 15.5

        如果 [g] 为 0 或缺失，使用 [cm3] × 材料密度计算。
        """
        mm = 0.0
        cm3 = 0.0
        grams = 0.0

        for line in lines:
            if "filament used [mm]" in line.lower():
                m = re.search(r"=\s*([\d.]+)", line)
                if m:
                    mm = float(m.group(1))
            elif "filament used [cm3]" in line.lower():
                m = re.search(r"=\s*([\d.]+)", line)
                if m:
                    cm3 = float(m.group(1))
            elif "total filament used [g]" in line.lower() or "filament used [g]" in line.lower():
                m = re.search(r"=\s*([\d.]+)", line)
                if m:
                    grams = float(m.group(1))

        # 如果克数为 0 但有 cm3，使用密度计算
        if grams <= 0 and cm3 > 0:
            pricing = config_service.MATERIAL_PRICING.get(material, {})
            density = pricing.get("density", 1.24)
            grams = cm3 * density
            logger.info("从体积换算重量: %.2f cm³ × %.2f g/cm³ = %.2f g", cm3, density, grams)

        return mm, cm3, grams

    def _extract_slicer_version(self, lines: list[str]) -> str:
        """
        从 G-code 头部提取切片器版本。
        匹配: ; generated by PrusaSlicer 2.9.4 on 2026-05-14
        """
        pattern = re.compile(r";\s*generated by (PrusaSlicer\s+[\d.]+)")
        for line in lines:
            m = pattern.match(line)
            if m:
                return m.group(1).strip()
        return "unknown"

    def _parse_time_string(self, time_str: str) -> float:
        """
        将 PrusaSlicer 时间字符串解析为总秒数。
        支持格式: "2h 34m 20s", "1h 5m", "45m 30s", "30s"
        """
        total = 0.0
        # 匹配小时
        h = re.search(r"(\d+)\s*h", time_str)
        if h:
            total += int(h.group(1)) * 3600
        # 匹配分钟
        m = re.search(r"(\d+)\s*m(?!o)", time_str)  # 排除 "mode"
        if m:
            total += int(m.group(1)) * 60
        # 匹配秒
        s = re.search(r"(\d+)\s*s", time_str)
        if s:
            total += int(s.group(1))
        return total

    def _count_layers(self, lines: list[str]) -> int:
        """通过统计 ;LAYER_CHANGE 注释或 G1 Z 变化来估算层数"""
        count = 0
        for line in lines:
            if line.strip().startswith(";LAYER_CHANGE"):
                count += 1
        return count
