; generated by PrusaSlicer 2.9.4 on 2026-05-14 at 14:42:46 UTC
;
G28 ; home
G1 Z0.2 F500
G1 X10 Y10 E0.5
;LAYER_CHANGE
G1 Z0.4
G1 X20 Y20 E1.0
;LAYER_CHANGE
G1 Z0.6
G1 X30 Y30 E1.5
;LAYER_CHANGE
; filament used [mm] = 150.5
; filament used [cm3] = 0.36
; total filament used [g] = 0.45
; estimated printing time (normal mode) = 5m 30s
